// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rizjgafyjuptieiqcwgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpempnYWZ5anVwdGllaXFjd2dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMDg4MDUsImV4cCI6MjA1NDc4NDgwNX0.x91ffXCU1P4Ob_NyM0jxtDNu678-Q6ExQaE7HtwWr-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);