// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuptfrtlgvzjzizcjrmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1cHRmcnRsZ3Z6anppemNqcm1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0MDQwNTYsImV4cCI6MjA1NDk4MDA1Nn0.ybJBeN8d6E0SLyZ3rKDEXgRiGUf3E1A8X6DMA9otkK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);